version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16.3.1
    working_directory: ~/repo
    steps: 
      - checkout
      - run:
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - restore_cache:
          keys:
          - app-{{ checksum "package.json" }}
          - app-  
      - run: 
          name: Install dependencies
          command: npm install
      - save_cache:
          paths: 
            - node_modules
          key: app_{{ checksum "package.json" }}
          
  deploy-to-aws-s3:
    docker:
    - image: circleci/node:16.3.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - run:
          name: Installing AWS CLI
          working_directory: /
          command: | 
            sudo apt-get -y -eq update
            sudo apt-get install -y awscli
            sudo apt-get install -y python-pip build-essential
      - run:
          name: Build Project
          command: |
            npm install
            npm run build
            cd build
            zip ../build.zip -r *.[^.]*
            echo "Build successful"
      - run:
          name: Deploy to AWS S3
          command: |
            if ["${CURRENT_BRANCH}" == "master"]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_PROD} --delete
            elif ["${CURRENT_BRANCH}" == "staging"]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_STAGING} --delete
            else
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_DEV} --delete
            fi


  deploy-to-aws-cloudfront:
    docker:
    - image: circleci/node:16.3.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - run:
          name: Installing AWS CLI
          working_directory: /
          command: | 
            sudo apt-get -y -eq update
            sudo apt-get install -y awscli
            sudo apt-get install -y python-pip build-essential
      - run:
          name: Build Project
          command: |
            npm install
            npm run build
            cd build
            zip ../build.zip -r *.[^.]*
            echo "Build successful"
      - run:
          name: Deploy to AWS Cloudfront
          command: |
            aws configure set preview.cloudfront
            if ["${CURRENT_BRANCH}" == "master"]
            then
              aws cloudfront create-invalidation --distribution-id ${PROD_DISTRIBUTION_ID} --paths /\*
            elif ["${CURRENT_BRANCH}" == "staging"]
            then
              aws cloudfront create-invalidation --distribution-id ${STAGING_DISTRIBUTION_ID} --paths /\*
            else
              aws cloudfront create-invalidation --distribution-id ${DEV_DISTRIBUTION_ID} --paths /\*
            fi


workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy_to_aws_s3:
          requires:
            - build
          filters:
             branches:
                only:
                  - dev
                  - staging
                  - prod
      
      - deploy_to_aws_cloudfront:
          requires:
            - deploy_to_aws_s3
          filters:
             branches:
                only:
                  - dev
                  - staging
                  - prod
                  